<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="SharpNinja.aiUnit" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.aiunit.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Avalonia.RemoteControl.Server\Avalonia.RemoteControl.Server.csproj" />
    <ProjectReference Include="..\..\src\Avalonia.RemoteControl.Client\Avalonia.RemoteControl.Client.csproj" />
    <ProjectReference Include="..\..\src\Avalonia.RemoteControl.Protocol\Avalonia.RemoteControl.Protocol.csproj" />
    <ProjectReference Include="..\..\src\Avalonia.RemoteControl.Runtime\Avalonia.RemoteControl.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Avalonia.RemoteControl.Tool\Avalonia.RemoteControl.Tool.csproj" />
  </ItemGroup>
</Project>
